### ISSUE TITLE
Disabling Bluetooth when disabling Wi-Fi (as the last active radio) doesn't work

### ISSUE THREAD

**Issue by valiantgenomics** [xKippi/gnome-shell-extension-sane-airplane-mode#6]
Thank you! For quite literally bringing back my 'sanity' with this extension. 

It boggles my mind why the GNOME WiFi - Airplane Mode - Bluetooth interactions are as such but they are annoying beyond words.

There's only 1 missing setting in the extension if I may:

![image](https://github.com/xKippi/gnome-shell-extension-sane-airplane-mode/assets/111633318/a8212e21-ca8b-46f2-9237-1e1616b65444)

When I disable my WiFi, the bluetooth gets enabled.

Is there a way to add a setting below the "Enable airplane mode" in the screenshot above which says "Enable bluetooth" so we can switch it off from there?

Again, thank you for creating this extension! Absolute sanity saver!!!

**Comment by AntiKippi** [comment]
Thank you for your nice words, I always appreciate that :).

The behavior you're describing is interesting... Not sure if this is a bug or a missing feature. I'll have a look at this if I find some time.

**Comment by valiantgenomics** [comment]
Awesome, thank you! Yes, please when/if you have some spare time consider looking into it. Thanks again for your selfless hard work, it's appreciated by all of us. People like yourself are the unsung heroes of the open source community. Truly.

**Comment by AntiKippi** [comment]
Hey I am unable to reproduce this behavior on my machine. What's your OS, OS version and GNOME Shell version?

**Comment by valiantgenomics** [comment]
Thanks a lot for the reply! This is my neofetch:

**OS: Pop!_OS 22.04 LTS x86_64 
Host: 81Q4 Legion Y540-17IRH 
Kernel: 6.2.6-76060206-generic 
DE: GNOME 42.5** 

To reproduce the problem, what I do is - start with disabled Bluetooth and enabled Wi-Fi.

Then when I disable my Wi-Fi, the Bluetooth automatically enables.

I have to manually disable it. 

And after I manually disable it, I can enable my Wi-Fi again, but this time the Bluetooth stays disabled. So the issue only happens when you go from enabled Wi-Fi to disabled Wi-Fi.

I recorded a 20 sec video showcasing the problem. Unfortunately, I can't upload it to github because it's a mp4 file, but I can upload it here:

https://file.io/hFBv4mXjjRLQ

Please let me know if I should provide any other info that may be helpful

**Comment by AntiKippi** [comment]
I am unfortunately still having a hard time reproducing this even in a Pop!_OS VM. Are you using the latest version of the extension?

But at least I have an idea now for the root cause. If I am correct this behavior shouldn't occur when 'Enable airplane mode' is enabled, can you confirm this?

Also can you try to execute the following command, press <kbd>Alt</kbd>+<kbd>F2</kbd>, type 'r' and hit <kbd>Enter</kbd> and tell me if the issue still persists:
``sed -i 's/DELAY = 100/DELAY = 500/' ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi/extension.js``

**Comment by valiantgenomics** [comment]
Hey! Yes, I believe I'm using the latest version of the extension:

![image](https://github.com/AntiKippi/gnome-shell-extension-sane-airplane-mode/assets/111633318/13535aef-cf98-4c52-9c73-6ca3587fac2d)

Ok, I ran the command and restarted GNOME as you suggested. Now interestingly, the Bluetooth still enables automatically after I disable the Wi-Fi but only for 1 sec and then disables automatically. I reckon that's to do with the DELAY?

And yes, you're totally right, this only occurs when 'Enable airplane mode' is enabled in the extension. When it's not enabled, I can disable Wi-Fi and the Bluetooth remains switched off.

**Comment by AntiKippi** [comment]
Alright now I am sure what's going on, the logic which disables Bluetooth after disabling the airplane mode (which is enabled when WiFi gets disabled) is executed too quickly.

I'm working on a more fail-save version now, stay tuned!

**Comment by valiantgenomics** [comment]
Awesome thank you so much! Should I reverse the command you told me to run above?

Your command was:

`sed -i 's/DELAY = 100/DELAY = 500/' ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi/extension.js`

I can reverse it by executing the opposite:

`sed -i 's/DELAY = 500/DELAY = 100/' ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi/extension.js`

Should I do that? Thanks!

**Comment by AntiKippi** [comment]
You're welcome! It doesn't really matter that much since this change will get overridden by the next update anyways but it fixes the problem for you so I'd suggest you keep it like that.

**Comment by AntiKippi** [comment]
Alrighty tighty I made some improvements to the failure safety, but currently I can't test them properly because I can't reproduce the delay issues.

Could you please get the current version in the dev branch and check if it works for you? You can do this by executing the following commands and restart the gnome-shell:
```
rm -rf ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi
git clone https://github.com/AntiKippi/gnome-shell-extension-sane-airplane-mode.git ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi
cd ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi
git checkout dev
```

**Comment by valiantgenomics** [comment]
Right thanks a lot for that! Ok, so first I reverted the command:

`sed -i 's/DELAY = 500/DELAY = 100/' ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi/extension.js`

Just to eliminate any conflicting variables and test it as if I were a normal user who has just updated the extension.

Then I deleted the default extension and ran the rm you suggested above:

`rm -rf ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi
git clone https://github.com/AntiKippi/gnome-shell-extension-sane-airplane-mode.git ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi
cd ~/.local/share/gnome-shell/extensions/sane-airplane-mode@kippi
git checkout dev`

It was successful and I logged out of my user, and logged back in to initiate the changes.

The dev extension was installed, and I can confirm it's the dev extension because clicking "more details" just tells me and error has occurred, rather than opening the default GNOME extension gateway page with all the reviews and supported GNOME versions.

However, unfortunately the Bluetooth still enables when I disable the Wi-Fi.

I can record the same video I shared previously, to showcase it but it's literally identical to what's shown in that video so I don't know how much value re-rerecording the same thing will provide.

And I can confirm again that when Enable Airplane Mode is enabled as the screenshot shows below, the Bluetooth remains switched off.

![image](https://github.com/AntiKippi/gnome-shell-extension-sane-airplane-mode/assets/111633318/07f37a6f-214b-49b8-b2ca-a43701c0e967)

**Comment by AntiKippi** [comment]
Huh I was wondering why you weren't replying to my new comment only to recognize that GitHub swallowed my email response.

Anyways, I implemented another major improvement to the disabling logic, could you please run the commands I told you last time again and tell me if it works now? You can confirm that you are using the dev version by checking the version (should be 13 now) and looking out for an "Advanced" menu in the settings.

Thank you for testing and looking forward to hearing from you!

**Comment by valiantgenomics** [comment]
Hey yeah, I deleted the extension and then ran the command again to get the latest dev version.

Unfortunately, the issue still persists and I believe I'm seeing some additional bugs with the airplane mode itself. Where once enabled it can't be disabled by clicking disable. And sometimes when airplane mode is enabled, the bluetooth also gets enabled.

I recorded a 1min video again to showcase everything because it will be much clearer than trying to put it into words.

https://file.io/bc4TyOkr0kom

Here's the video. Thanks a lot for your persistence!! I'll keep troubleshooting with you for as long as it takes without any problems, or until you deem it unfixable.

**Comment by AntiKippi** [comment]
Thanks for the testing. It's really annoying not to be able to reproduce this myself.

Could you please turn on the debug log option in the advanced settings, test it again and then send me your GNOME shell log (obtainable via `journalctl /usr/bin/gnome-shell -S "10 minutes ago" --no-hostname`)?

**Comment by valiantgenomics** [comment]
> Thanks for the testing. It's really annoying not to be able to reproduce this myself.
> 
> Could you please turn on the debug log option in the advanced settings, test it again and then send me your GNOME shell log (obtainable via `journalctl /usr/bin/gnome-shell -S "10 minutes ago" --no-hostname`)?

Hey sorry was out of town due to work, but I'm back on the regular now. 

Here's the output: https://pastebin.com/31dGwgV0

I disabled and enabled the Wi-Fi a few times, and then ran the journalctl command.

It's very weird that you can't reproduce the bug even in a PopOS VM. Could it be some weird interaction with another extension?

Here's all the extensions I'm running:

https://file.io/S53TLRoNeaGx

**Comment by AntiKippi** [comment]
Thank you for the testing and everything. For my late response, I also was away some time now.

And thanks for the log, but unfortunately it is missing the relevant entries (There should be lines like this: `Aug 03 00:00:00 gnome-shell[1270]: Sane Airplane Mode: Begin executing handleAirplaneModeChange`).

May I ask you redo it, but make sure you have enabled the "Enable debug log" switch in the Advanced settings, include the _whole_ output of the command and make sure there is less than 10 minutes of time between the testing and the log taking?

And as for the extensions I've looked through them but couldn't find one which could cause a interaction. My guess for why I can't reproduce it are some device specific characteristics of yours.

**Comment by valiantgenomics** [comment]
Yeah no probs! I redid the debugging again, but I cannot see any "Sane Airplane Mode" entries in the logs.

I recorded a 30sec video again showing you the entire process, so you can see whether I'm doing it right.

https://file.io/3U1FuMEwqkWS

And also here's the log output itself: https://pastebin.com/TdtC1N3d

**Comment by AntiKippi** [comment]
Ah yeah I see. I think you copied only the first 35 lines of the log, which only includes the oldest entries. Please try executing `journalctl /usr/bin/gnome-shell -S "10 minutes ago" --no-hostname > /tmp/sam.log` instead and gimme the whole content of the file /tmp/sam.log :).

**Comment by valiantgenomics** [comment]
Great! I ran that and here's the whole sam.log file:

https://file.io/uSLFSpjtwOSv

Hopefully that has enough info to get some more clarity!!
